export const VaccineTypeEnum = {
  HEPATITISB: 1,
  BCG: 2,
  HIB: 3,
  IPV: 4,
  PCV: 5,
  PENTAVALENT: 6,
  ROTAVIRUS: 7,
  INFLUENZA: 8,
  MMR: 9,
  VARICELLA: 10,
  HEPATITISA: 11,
  DTAP: 12,
  HPV: 13,
  MENINGOCOCCAL: 14,
};

export const VaccineTypes = {
  1: "Hepatitis B",
  2: "BCG",
  3: "Pentavalent",
  4: "Inactivated Polio",
  5: "Pneumococcal",
  6: "Pentavalent ",
  7: "Rotavirus",
  8: "Influenza ",
  9: "MMR ",
  10: "Varicella",
  11: "DTaP",
  12: "IPV",
  13: "Human Papillomavirus",
  14: "Meningococcal Conjugate",
};
